# -*- coding: utf-8 -*-
"""sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1msdRaOEaS-nXDjwT4sQddtvFU0jdXO5f
"""

import pandas as pd
df = pd.read_csv("/content/sales_forecasting_dataset.csv")

df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)

df = df.sort_index()

df = df.fillna(method='ffill')

import matplotlib.pyplot as plt

df['Sales'].plot(figsize=(10,5))
plt.title("Sales Over Time")
plt.show()

train = df[:'2023-12']
test = df['2024-01':]

from statsmodels.tsa.arima.model import ARIMA

model = ARIMA(train['Sales'], order=(5,1,0))
model_fit = model.fit()

forecast = model_fit.forecast(steps=len(test))

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(test['Sales'], forecast)
print("MAE:", mae)

plt.figure(figsize=(10,5))
plt.plot(train.index, train['Sales'], label='Train')
plt.plot(test.index, test['Sales'], label='Actual')
plt.plot(test.index, forecast, label='Forecast')

plt.legend()
plt.title("Forecast vs Actual Sales")
plt.show()

